# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Canvas2Extent
                                 A QGIS plugin
 Automatic Canvas to layout extent
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-20
        copyright            : (C) 2026 by Giuseppe De Marco
        email                : demarco.giuseppe@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Canvas2Extent class from file Canvas2Extent.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .canvas2extent import Canvas2Extent
    return Canvas2Extent(iface)
