# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'canvas2extent_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Canvas2ExtentDialogBase(object):
    def setupUi(self, Canvas2ExtentDialogBase):
        Canvas2ExtentDialogBase.setObjectName("Canvas2ExtentDialogBase")
        Canvas2ExtentDialogBase.resize(295, 363)
        font = QtGui.QFont()
        font.setFamily("Arial")
        Canvas2ExtentDialogBase.setFont(font)
        self.Update = QtWidgets.QPushButton(Canvas2ExtentDialogBase)
        self.Update.setGeometry(QtCore.QRect(30, 180, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Update.setFont(font)
        self.Update.setObjectName("Update")
        self.ComboLayout = QtWidgets.QComboBox(Canvas2ExtentDialogBase)
        self.ComboLayout.setGeometry(QtCore.QRect(30, 130, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ComboLayout.setFont(font)
        self.ComboLayout.setObjectName("ComboLayout")
        self.line = QtWidgets.QFrame(Canvas2ExtentDialogBase)
        self.line.setGeometry(QtCore.QRect(-20, 40, 311, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Title = QtWidgets.QLabel(Canvas2ExtentDialogBase)
        self.Title.setGeometry(QtCore.QRect(10, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Title.setTextFormat(QtCore.Qt.PlainText)
        self.Title.setWordWrap(True)
        self.Title.setObjectName("Title")
        self.Load = QtWidgets.QPushButton(Canvas2ExtentDialogBase)
        self.Load.setGeometry(QtCore.QRect(30, 50, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Load.setFont(font)
        self.Load.setObjectName("Load")
        self.label = QtWidgets.QLabel(Canvas2ExtentDialogBase)
        self.label.setGeometry(QtCore.QRect(196, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c2v_icon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Quit = QtWidgets.QPushButton(Canvas2ExtentDialogBase)
        self.Quit.setGeometry(QtCore.QRect(30, 320, 231, 31))
        icon = QtGui.QIcon.fromTheme("quit")
        self.Quit.setIcon(icon)
        self.Quit.setObjectName("Quit")
        self.ShowL = QtWidgets.QPushButton(Canvas2ExtentDialogBase)
        self.ShowL.setEnabled(False)
        self.ShowL.setGeometry(QtCore.QRect(30, 250, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ShowL.setFont(font)
        self.ShowL.setObjectName("ShowL")

        self.retranslateUi(Canvas2ExtentDialogBase)
        self.Load.clicked.connect(Canvas2ExtentDialogBase.exec) # type: ignore
        self.Update.clicked.connect(Canvas2ExtentDialogBase.exec) # type: ignore
        self.ComboLayout.activated['QString'].connect(Canvas2ExtentDialogBase.exec) # type: ignore
        self.Quit.clicked.connect(Canvas2ExtentDialogBase.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Canvas2ExtentDialogBase)

    def retranslateUi(self, Canvas2ExtentDialogBase):
        _translate = QtCore.QCoreApplication.translate
        Canvas2ExtentDialogBase.setWindowTitle(_translate("Canvas2ExtentDialogBase", "Canvas2Extent"))
        self.Update.setText(_translate("Canvas2ExtentDialogBase", "UPDATE LAYOUT EXTENT"))
        self.Title.setText(_translate("Canvas2ExtentDialogBase", "Canvas2Extent by Giuseppe De Marco 2026"))
        self.Load.setText(_translate("Canvas2ExtentDialogBase", "LOAD LAYOUTS"))
        self.Quit.setText(_translate("Canvas2ExtentDialogBase", "QUIT"))
        self.ShowL.setText(_translate("Canvas2ExtentDialogBase", "SHOW UPDATED LAYOUT"))
